version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "wasmtime*"
      - dependency-name: "wit-bindgen*"
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/crates/ext-processor/protobuf/protoc-gen-validate"
    schedule:
      interval: "monthly"
    labels: []
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "gomod"
    directory: "/crates/ext-processor/protobuf/protoc-gen-validate"
    schedule:
      interval: "monthly"
    labels: []
    ignore:
      - dependency-name: "*"
