sensitiveCodepaths:
  # Files only allowed authors can modify
  - ".github/**/*"
allowedAuthors:
  usernames:
    # GitHub username
    - "sporkmonger"
    - "dependabot"
    - "dependabot[bot]"
notificationList:
  # GitHub username or team name
  - "@sporkmonger"
