sensitiveCodepaths:
  # Files only allowed authors can modify
  - '.github/**/*'
allowedAuthors:
  usernames:
    # GitHub username
    - 'sporkmonger'
notificationList:
  # GitHub username or team name
  - '@sporkmonger'
