[package]
name = "bulwark-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulwark-ext-filter = { path = "crates/ext-filter" }
serde = { version = "1.0.149", features = ["std", "serde_derive"] }
toml = { version = "0.5.9", features = ["preserve_order"] }
anyhow = "1.0.66"
thiserror = "1.0.37"

[workspace]
members = ["crates/ext-filter", "crates/wasm-host", "crates/wasm-sdk"]
