[package]
name = "bulwark-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulwark-ext-filter = { path = "crates/ext-filter" }

[workspace]
members = [
    "crates/core",
    "crates/ext-filter",
    "crates/wasm-host",
    "crates/wasm-sdk",
]
