[package]
name = "bulwark-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulwark-ext-filter = { path = "crates/ext-filter" }
bulwark-config = { path = "crates/config" }
anyhow = "1.0.66"
thiserror = "1.0.37"
clap = { version = "4.0.29", features = ["derive"] }
clap_complete = "4.0.6"
# TODO: used for debug currently, remove later
serde = { version = "1.0.149", features = ["std", "serde_derive"] }
toml = { version = "0.5.9", features = ["preserve_order"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "tracing"] }
envoy-control-plane = { version = "0.4.0", features = ["grpc"] }
tonic = "0.6.2"
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.4"
tracing-opentelemetry = "0.18.0"
tracing-forest = { version = "0.1.5", features = ["tokio"] }
tracing-appender = "0.2.2"
tracing-futures = { version = "0.2.5", features = ["tokio"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
color-eyre = "0.6.2"
tower-http = { version = "0.4.0", features = ["tokio", "tracing", "request-id", "trace"] }
http = "0.2"
hyper = { version = "0.14.25", features = ["server"] }
tower = { version = "0.4.13", features = ["tokio", "tracing"] }

[build-dependencies]
clap_mangen = "0.2.5"

[workspace]
members = [
    "crates/config",
    "crates/ext-filter",
    "crates/wasm-host",
    "crates/wasm-sdk",
]
