[package]
name = "bulwark-config"
version = "0.1.0"
edition = "2021"

[dependencies]
bulwark-wasm-sdk = { path = "../wasm-sdk" }
serde = { version = "1.0.149", features = ["std", "serde_derive"] }
serde_json = "1.0.93"
toml = { version = "0.5.9", features = ["preserve_order"] }
anyhow = "1.0.66"
thiserror = "1.0.37"
chrono = { version = "0.4.23", features = ["serde"] }
