[package]
name = "bulwark-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.149", features = ["std", "serde_derive"] }
toml = { version = "0.5.9", features = ["preserve_order"] }
anyhow = "1.0.66"
thiserror = "1.0.37"
