[package]
name = "bulwark-core"
version = "0.1.0"
authors = ["Bob Aman <bob@sporkmonger.com>"]
edition = "2021"

[dependencies]
num = "0.4"
validator = { version = "0.12", features = ["derive"] }
approx = "0.4"
thiserror = "1.0.37"
bulwark-wasm-host = { path = "../wasm-host" }
