[package]
name = "bulwark-decision"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
validator = { version = "0.12", features = ["derive"] }
approx = "0.4"

[dev-dependencies]
cfg-if = "1.0"
