name: 'Dependency Checks'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'cargo deny'
      uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check
        command-arguments: licenses
