name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@00b49be78f40fba4e87296b2ead62868750bdd83
        with:
          toolchain: stable
          components: rustfmt

      - run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true
          target: wasm32-wasi

      - name: Rust cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: Run clippy
        run: cargo clippy --no-deps --workspace --all-targets -- --deny warnings

  test:
    name: Test suite
    strategy:
      fail-fast: false
      matrix:
        rust_version:
          - stable
        os:
          - ubuntu-latest
        redis-version:
          - "6.2.14"
          - "7.2.4"
        envoy-version:
          - "1.22"
          - "1.26"
          - "1.29"
        exclude:
          - redis-version: "6.2.14"
            envoy-version: "1.22"
          - redis-version: "6.2.14"
            envoy-version: "1.29"

    runs-on: ${{ matrix.os }}

    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      echo:
        image: hashicorp/http-echo
        ports:
          - 5678:5678

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Launch Envoy service
        run: /usr/bin/docker run -d --name envoy --network "${{ job.container.network }}" --network-alias envoy -p 8080:8080 -e GITHUB_ACTIONS=true -e CI=true -v "./tests/gha_envoy.yaml":"/etc/envoy/envoy.yaml" envoyproxy/envoy:v${{ matrix.envoy-version }}-latest envoy -l debug -c /etc/envoy/envoy.yaml

      - name: Install Rust
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: ${{ matrix.rust_version }}
          components: clippy
          override: true
          target: wasm32-wasi

      - name: Rust cache
        uses: swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

      - name: Docker services
        run: /usr/bin/docker ps

      - name: Run bulwark tests
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
        with:
          command: test
          args: -p bulwark-cli -p bulwark-build -p bulwark-config -p bulwark-decision -p bulwark-ext-processor -p bulwark-wasm-host -p bulwark-wasm-sdk -p bulwark-wasm-sdk-macros -- --include-ignored

      - name: Envoy logs
        run: /usr/bin/docker logs envoy

      - name: Kill Envoy service
        run: /usr/bin/docker kill envoy
